### ISSUE TITLE
Schema default values not used

### ISSUE THREAD

**Issue by HarrisInfiot** [gae123/sd2#4]
Version 0.14.1 shuts down with `WARNING MAIN:LOOP:EX 'config'` if there is no `config` key in config.yaml. Expected result was the config to include default values from the schema but it appears not to be working properly. Will investigate further and update this issue with findings and possibly a PR

**Comment by gae123** [comment]
Not sure what happens here. This definitely does not happen in my MacOS environment. The workaround seems to be to add these entries in the config.yaml. It is expected that when these values are missing, they are picked up from the schema defaults.

```
config:
  HaltOnSuspendResume: yes
  DockerCheckPeriodInSeconds: 60
  RsynCheckPeriodInSeconds: 3000
```
